import { getRandomScreenPosition } from "../utils/getRandomScreenPosition";
import { ActorKind } from "./ActorKind";
import { Color } from "excalibur";
import Game from "./Game";
import { ActorBase } from "./Base";
import { randomBetween } from "../utils/helpers";

// an array of 100 real names of stars
const starNames = [
  "Sirius",
  "Alpha Centauri",
  "Betelgeuse",
  "Rigel",
  "Vega",
  "Procyon",
  "Achernar",
  "Canopus",
  "Altair",
  "Capella",
  "Rigil Kentaurus",
  "Arcturus",
  "Aldebaran",
  "Spica",
  "Antares",
  "Pollux",
  "Fomalhaut",
  "Deneb",
  "Mimosa",
  "Regulus",
  "Adhara",
  "Castor",
  "Shaula",
  "Bellatrix",
  "Elnath",
  "Miaplacidus",
  "Alnilam",
  "Alnair",
  "Alnitak",
  "Alioth",
  "Alphard",
  "Algieba",
  "Almach",
  "Alrescha",
  "Alruccabah",
  "Alsciaukat",
  "Alshain",
  "Altarf",
  "Ankaa",
  "Anser",
  "Arkab",
  "Arkab Posterior",
  "Aspidiske",
  "Avior",
  "Azha",
  "Becrux",
  "Beid",
  "Benetnasch",
  "Betria",
  "Botein",
  "Brachium",
  "Canopus",
  "Caph",
  "Cheleb",
  "Chertan",
  "Chort",
  "Dabih",
  "Delphini",
  "Deneb Algedi",
  "Denebola",
  "Diphda",
  "Dschubba",
  "Dubhe",
  "Edasich",
  "Elgafar",
  "Eltanin",
  "Enif",
  "Epsilon Crucis",
  "Epsilon Eridani",
  "Epsilon Scorpii",
  "Epsilon Tauri",
  "Eridani",
  "Fomalhaut",
  "Fumalsamakah",
  "Gacrux",
  "Garnet Star",
  "Giausar",
  "Gienah",
  "Gienah Ghurab",
  "Girtab",
  "Gomeisa",
  "Gorgonea Tertia",
  "Graffias",
  "Grumium",
  "Hadar",
  "Hamal",
  "Han",
  "Hassaleh",
  "Hatysa",
  "Heze",
  "Izar",
  "Kaffaljidhma",
  "Kajam",
  "Kaus Australis",
  "Kaus Borealis",
  "Kaus Media",
  "Kaus Meridionalis",
  "Keid",
  "Kitalpha",
  "Kochab",
  "Kornephoros",
  "Kraz",
  "Kuma",
  "La Superba",
  "Lesath",
  "Maasym",
  "Marfik",
  "Markab",
  "Markeb",
  "Matar",
  "Mebsuta",
  "Megrez",
  "Meissa",
  "Menkalinan",
  "Menkar",
  "Menkent",
  "Menkib",
  "Merak",
  "Miaplacidus",
  "Mimosa",
  "Mintaka",
  "Mira",
  "Mirach",
  "Mirfak",
  "Mirzam",
  "Misam",
  "Mizar",
  "Mothallah",
  "Muhlifain",
  "Muliphen",
  "Nashira",
  "Navi",
  "Nekkar",
  "Nihal",
  "Nunki",
  "Nusakan",
  "Peacock",
  "Phact",
  "Phecda",
  "Pherkad",
  "Polaris",
  "Pollux",
  "Porrima",
  "Praecipua",
  "Prima Hyadum",
  "Procyon",
  "Propus",
  "Ras Algethi",
  "Rasalhague",
  "Rastaban",
  "Rigel Kentaurus",
  "Rijl al Awwa",
  "Rotanev",
  "Ruchbah",
  "Rukbat",
  "Sabik",
  "Sadachbia",
  "Sadalmelik",
  "Sadalsuud",
  "Saiph",
  "Salm",
  "Sargas",
  "Scheat",
  "Schedar",
  "Shaula",
  "Sheliak",
  "Sheratan",
  "Sirius",
  "Situla",
  "Skat",
  "Spica",
  "Sualocin",
  "Subra",
  "Suhail",
  "Sulafat",
  "Syrma",
  "Tabit",
  "Talitha",
  "Tarazed",
  "Taygeta",
  "Tegmine",
  "Thuban",
  "Tien Kuan",
  "Toliman",
  "Torcularis Septentrionalis",
  "Unukalhai",
  "Vega",
  "Vindemiatrix",
  "Wasat",
  "Wezen",
  "Yed Posterior",
  "Yed Prior",
  "Yildun",
  "Zaniah",
  "Zaurak",
  "Zavijava",
  "Zosma",
  "Zubenelgenubi",
  "Zubenelhakrabi",
  "Zubeneschamali",
];

function getRandomStarName() {
  return starNames[Math.floor(Math.random() * starNames.length)];
}

export class Star extends ActorBase {
  public kind: ActorKind = ActorKind.Star;
  constructor(options?: { name?: string; kind?: ActorKind }) {
    super({
      width: 2,
      height: 2,
      name: getRandomStarName(),
      color: Color.White,
      ...options,
    });
  }

  onInitialize(engine: Game): void {
    this.pos = getRandomScreenPosition(engine);
    this.startTimer(() => this.next());
    this.setStatus({
      journal: [
        {
          action: "Became a star",
          state: "big and bright",
          timestamp: Date.now(),
        },
      ],
    });
  }

  next() {
    this.actions
      .callMethod(() => {
        this.color = Color.DarkGray;
      })
      .delay(randomBetween(300, 1000))
      .callMethod(() => {
        this.color = Color.White;
      });
  }
}
